services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=mix2559za
      - POSTGRES_USER=kanyatipat
      - POSTGRES_DB=kanyatipat
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=kanyatipat@example.com
      - PGADMIN_DEFAULT_PASSWORD=mix2559za
    volumes:
      - ./data-pgadmin:/var/lib/pgadmin
