services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    environment:
      POSTGRES_PASSWORD: mix2559za
      POSTGRES_USER: kanyatipat
      POSTGRES_DB: kanyatipat
    volumes:
      - ./data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s1-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: kanyatipat@admin.com
      PGADMIN_DEFAULT_PASSWORD: mix2559za
    ports:
      - "8080:80"
    depends_on:
      - db
